#!/usr/bin/env bash
#Configure domain zone so that the subdomain www points to your load-balancer IP (lb-01)

dns_info ()
{
domain="$1"
subdomain="$2"
dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

if [ "$#" == 2 ]
then
dns_info "$1" "$2"
elif [ "$#" == 1 ]
then
dns_info "$1" "www"
dns_info "$1" "lb-01"
dns_info "$1" "web-01"
dns_info "$1" "web-02"
fi
