#!/usr/bin/env bash
#install load balancer

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\* --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

sudo echo -e "
frontend haproxy-main
\tbind *:80
\tdefault_backend webservers
backend webservers
\tbalance roundrobin
\tserver XXX-web-01\t44.211.30.87:80 check
\tserver XXX-web-02\t44.210.121.85:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
