#!/usr/bin/bash
#This configures a server to the above requirements

sudo rm /etc/nginx/sites-enabled/default
ln /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
sudo service nginx restart
