#!/usr/bin/env bash
#This scripts displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
While true
doecho "To infinity and beyond"
sleep 2
done
