#!/usr/bin/env bash
#This script displays the content of the file /etc/passwd, using the while loop + IFS.

FILENAME="/etc/passwd"
while IFS=: read -r username password uid gid comment homedir cmd
do
echo "The user $username is part of the $gid gang, lives in $homedir and rides $cmd. $uid's place is protected by the passcode $password, more info about the user here: $comment"
done < $FILENAME
