#!/usr/bin/env bash
#This scripts displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

i=0
while [ $i -lt 10 ]
do 

if [ $i -eq 9 ]
then 
echo "Best School"
else
echo "Hi"

fi
i=$(( i + 1))
done
