#!/usr/bin/env bash
#displays:
#The content of the current directory In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for i in *
doecho "$i" cut 8d '-' -f 2;
done
